### ISSUE TITLE
ICP lost in swap process

### ISSUE THREAD

**Issue by tarek-eg** [iclighthouse/Cycles.Finance#1]
Hello,
I have an issue while swapping from icp to cycles 
I transfered `9.9999 ICP` with this transaction id to my deposit account
transaction id: 
[d79b0c83654dca005ce3b69b1bf9809cdbe6e0d8f4721e39e1d2bcb362860d47](https://dashboard.internetcomputer.org/transaction/dacd9543b59e7455edb42e0bf427806895b2a4353069b923b317d2bb2fb74746)

And then tried to swap 10 icp to cycles but I got a message that the amount was too large so I changed the amount to 5 icp.
But I found that the whole amount was deducted from my balance anyway 
transaction id of the 10 ICP deduction:
[d79b0c83654dca005ce3b69b1bf9809cdbe6e0d8f4721e39e1d2bcb362860d47](https://dashboard.internetcomputer.org/transaction/d79b0c83654dca005ce3b69b1bf9809cdbe6e0d8f4721e39e1d2bcb362860d47)

I could still convert 4.9 ICP and get that result
```
{
  ok: {
    shares: { NoChange: null },
    icpE8s: { DebitRecord: 499990000n },
    txid: [
        0,  0,   0,   2, 168, 253, 221, 223,
       17, 78,  15, 254, 198,  26, 103, 169,
      251, 87, 206, 169, 201,  62, 122, 185,
      158, 46, 184,  79,  95, 136, 150,  71
    ],
    cycles: { CreditRecord: 109723657414864n }
  }
}
```

So I am expecting that I have still 5 icp but when I try to swap icp to cycles again I get Invalid ICP amount error.
Thanks,

**Comment by tarek-eg** [comment]
The issue has happened again, I suspect the issue happens when a call to the minting function `icpToCycles` is rejected.
This time I tried with 2 icps and only minted 18TC equals to 1 ICP.
```
(
  variant {
    5_048_165 = record {
      1_103_409_453 = variant { 3_065_948_643 };
      2_584_819_143 = "Invalid ICP amount.";
    }
  },
)
```
the new transaction [4b6453281b0034de16293778b05c294cb5c45f5f96e9140a207f71e09df89658](https://dashboard.internetcomputer.org/transaction/4b6453281b0034de16293778b05c294cb5c45f5f96e9140a207f71e09df89658)

**Comment by iclighthouse** [comment]
0ab0470f1e57abdac680f2610e5cf770b1dd1f29aff40dbc6b7a7446c31e0260 is your Account.

After a swap transaction has been rejected, the icp will be refunded with a delay (the refund will be made when the next valid transaction occurs). Please check if the final balance is consistent?
https://dashboard.internetcomputer.org/transaction/119f237d14fc93687d4a637e2e513c96e366120095238367a8503cd0a74c29ff This transaction should be a refund.

This is a issue. We will implement instant refunds in the next version, which is currently being tested.

Translated with www.DeepL.com/Translator (free version)

**Comment by iclighthouse** [comment]
[17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4](https://dashboard.internetcomputer.org/account/17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4) is your Account.

7bdbc661e4aa74b9d3fe7b8b88dcdeb46a927ddcd4facddddf03e34d337dddcd is your DepositAccount in CyclesFinance.

But your icp is sent from account **0ab0470f1e57abdac680f2610e5cf770b1dd1f29aff40dbc6b7a7446c31e0260** to DepositAccount. So the refund is returned to account **17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4**.

https://dashboard.internetcomputer.org/transaction/5e4f21ccd67acf43d0ee3a39a20875cb098287a9ca9336cc1448032e7df1555f
https://dashboard.internetcomputer.org/transaction/dc2fe3fdcb04b05ec525945012d660b4fe2c52d5833a0b5785a3d7c2c6759efc

**Comment by tarek-eg** [comment]
Thanks for the reply.
I didn't know that **17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4** is my account.
How do I access that account and withdraw my fund?
Is there a way to refund the amounts to **0ab0470f1e57abdac680f2610e5cf770b1dd1f29aff40dbc6b7a7446c31e0260** instead?

**Comment by iclighthouse** [comment]
This is unlikely to be the case if using the UI. are you using the command line to do this?

Did you fill in the _sa parameter of the icpToCycles method? If you filled it in, do you remember what was filled in?
The _sa indicates that you are specifying a sub-account as your Account-id.

### Method 1

`dfx ledger --network ic account-id`
`dfx ledger --network ic balance`
Executing the two commands above. 
Can you see your account 17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4 and balance?  
If you can see it, you can use the dfx ledger command line to transfer ICP.

### Method 2

try with this command:
`dfx canister --network ic call ryjl3-tyaaa-aaaaa-aaaba-cai transfer '(record{ to=<Your_Receiving_Account>; amount=record{ e8s=600960000:nat64 };  amount=record{ e8s=10000:nat64 }; memo=0:nat64; from_subaccount=opt <Your_SubAccount>})'`
- <Your_Receiving_Account>: **blob**, Your ICP account, which needs to be converted to a blob type.
- <Your_SubAccount>: **blob**, The _sa parameter you used to fill in the icpToCycles method.

**Comment by tarek-eg** [comment]
For `icpToCycles` I was using dfx cli and was passing null in the params

`
dfx canister --network ic call 6nmrm-laaaa-aaaak-aacfq-cai icpToCycles '(100000000:nat, principal "ae7k3-wyaaa-aaaah-qacyq-cai", null, null, null)'
`
So if I was passing null in the `_sa` param how the command should like like knowing that I want to transfer to my account
`0ab0470f1e57abdac680f2610e5cf770b1dd1f29aff40dbc6b7a7446c31e0260`

I know [ic.rocks](https://ic.rocks/tools/blob) has a tool to do that but I don't want to risk making a transfer mistake.

**Comment by iclighthouse** [comment]
Both 0ab0470f1e57abdac680f2610e5cf770b1dd1f29aff40dbc6b7a7446c31e0260 and 17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4 belong to the accounts you control and only you have the private key. Otherwise the transaction cannot be sent.

execute:
`dfx ledger --network ic account-id  `
`dfx ledger --network ic balance`

What was returned?

**Comment by tarek-eg** [comment]
`dfx ledger --network ic account-id`
`f097e06ed397cd902ce0dff6c7068abd6145e0cbbdc0c03f126aad50e20d7b00`

`dfx ledger --network ic balance`
`0.00000000 ICP`

**Comment by tarek-eg** [comment]
Would it be helpful if we debug this together

**Comment by iclighthouse** [comment]
> `dfx canister --network ic call 6nmrm-laaaa-aaaak-aacfq-cai icpToCycles '(100000000:nat, principal "ae7k3-wyaaa-aaaah-qacyq-cai", null, null, null)'`
> So if I was passing null in the `_sa` param how the command should like like knowing that I want to transfer

The caller account in command line is "17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4"

`dfx ledger --network ic account-id` It should return "17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4"

Why are your accounts in flux?

**Comment by iclighthouse** [comment]
> Would it be helpful if we debug this together

This involves your private key and I expect you to do it independently.

**Comment by tarek-eg** [comment]
> > Would it be helpful if we debug this together you can find my telegram here https://t.me/tarek_m_eg
> 
> This involves your private key and I expect you to do it independently.

I understand,
The issue could be that I used `agent-js` identity which returns a different principal and account than the one used by `dfx` even with the same private keys.
https://forum.dfinity.org/t/how-to-use-my-local-private-keys-in-agent-js/9456/3

**Comment by iclighthouse** [comment]
If you use a temporary account each time and do not back up your private keys, you will lose these ICPs forever.
If your terminal saves the private keys, e.g. in the agent.js directory, you can try to retrieve them.

**Comment by tarek-eg** [comment]
I have the private keys stored in my machine, the issue is I need to use agent-js identity to transfer these amounts, and as far as I know the `ledger` doesn't have a candid interface to do that to be used in nodejs script.

**Comment by iclighthouse** [comment]
Which terminal were you using to execute icpToCycles?

What account will be returned if you execute this in that terminal?
`dfx ledger --network ic account-id`

**Comment by tarek-eg** [comment]
I used both a nodejs script and dfx

`dfx ledger --network ic account-id`
`f097e06ed397cd902ce0dff6c7068abd6145e0cbbdc0c03f126aad50e20d7b00`


identity in js script is created like this
```
import { Secp256k1KeyIdentity } from "@dfinity/identity";
import sha256 from "sha256";
import { readFileSync } from "fs";

const initIdentity = () => {
  const rawKey = readFileSync(process.env.PATH_TO_PRIVATE_KEY!)
    .toString()
    .replace("-----BEGIN EC PRIVATE KEY-----", "")
    .replace("-----END EC PRIVATE KEY-----", "")
    .trim();

  const rawBuffer = Uint8Array.from(rawKey).buffer;
  const privKey = Uint8Array.from(sha256(rawBuffer, { asBytes: true }));
  const identity = Secp256k1KeyIdentity.fromSecretKey(
    Uint8Array.from(privKey).buffer,
  );
  return identity;
};
```

**Comment by iclighthouse** [comment]
Which account did you use to execute icpToCycles() at the time?

https://k7gat-daaaa-aaaae-qaahq-cai.ic0.app/listing/nns-ledger-10244
This is the did of Ledger (Candid, Motoko, TypeScript, JavaScript)

**Comment by tarek-eg** [comment]
That might be helpful.
Let me try to use that.
Any idea how can I change the account `17ec70cc9a16677967530fcfa816e67627fcbd23aba9f9632b1e6debe7e340b4`
to a `Array<number>`
`interface AccountBalanceArgs { 'account' : Array<number> };`

**Comment by tarek-eg** [comment]
Thanks,
I was able to transfer the remaining amount using [the nns ledger](https://k7gat-daaaa-aaaae-qaahq-cai.ic0.app/listing/nns-ledger-10244)
Appreciate your help and your time.
